---
  title: "Results of Logarithmic encoding model"
author: "Fiona Zhu"
date: "15/7/2020"
output:
  html_document:
  df_print: paged
pdf_document: default
word_document: default
---
  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
## Load the packages and include functions
library(rlist)
library(tidyverse)
library(rstan)

sizeInModel <- c(1, 2, 3)
colorSet3 <- scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9")) 
colorSet4 <- scale_color_manual(values=c("#999999", "#E69F00", "#56B4E9", "#1a9641")) 
colorSet <- scale_color_manual(values=c("#d7191c", "#fdae61", "#a6d96a", "#1a9641")) 

rootPath = '/Users/jiaowu/Documents/OpenAccessCodes/Zang_WM_durRep/'
codePath = paste0(rootPath, 'analysis/')
dataPath = paste0(rootPath, 'data/')
stanCodePath = paste0(codePath, 'RStanCode/')
```

Note that the WMSize in models are using 1, 2, 3 instead of 1,3,5.

```{r include=FALSE}
options(mc.cores = parallel::detectCores()-1)
rstan_options (auto_write=TRUE)
setwd(codePath)
source('gap_rstan_log.R') 
#source('rstan_linear.R')
rstanmodelPath = 'modelrlt'
modelversion = 'gap_log_rstan'
modelPath = paste0(rstanmodelPath, '/models/', modelversion)
library(ggpubr)
```


```{r include=FALSE}
## read data
dat <- read.csv(paste0(dataPath, "AllValidData.csv"))
AllExpData <- dat %>% filter(Exp=="Exp5") # repDur>0.1 & repDur<2.5
AllExpData$log_RP <- log(AllExpData$repDur)
AllExpData$log_dur <- log(AllExpData$curDur)
AllExpData$Gap <- AllExpData$Gap * 1000

# max(AllExpData$repDur)
AllExpData
```

###  run models to compute parameters 

```{r include=FALSE}
# load the model
myrstanModel  <- stan_model(file=paste0(stanCodePath, modelversion,".stan"))

```

```{r include=FALSE}
# function to run models on local computer
noEffect = FALSE  #when parameter noEffect is true marks all data fits with exp1 model 
if(noEffect){
  modelversion = 'log_stan_noeffect'
  modelPath = paste0(rstanmodelPath, '/models/', modelversion)
}

runModelonlocal<- function(AllExpData, myrstanModel){
  expList <- unique(AllExpData$Exp)
  # expList = c('Exp2', 'Exp3', 'Exp4')
  # subList <- unique(AllExpData$NSub)
  subList <- unique(AllExpData$NSub)[0:1]
  
  for (expName in expList) {
    Allrlt <- list()
    data_exp <- AllExpData %>% dplyr::filter(Exp == expName)
    data_exp$model <- expName
    sub_exp <-  split(data_exp, data_exp$NSub) # split data for each subject
    for (subNo in subList) {
      rlt <-  funFitStan(sub_exp[[subNo]], myrstanModel, noEffect)
      saveRDS(rlt, file = paste0(getwd(), "/", modelPath, "/rlt/rlt_", expName,"_sub",subNo,".rds"))
      Allrlt <- list.append(Allrlt,rlt)
    }
    saveRDS(Allrlt, file = paste0(getwd(), "/", modelPath, "/rlt/rlt_", expName,".rds"))
  }
}

runModelonlocal(AllExpData, myrstanModel)
```

```{r include=FALSE}
# combine rds for each participant
subList <- unique(AllExpData$NSub)
Allrlt <- list()
for (subNo in subList) {
      rlt <- readRDS(paste0(modelPath, "/rlt/rlt_Exp5_sub",subNo,".rds"))
      Allrlt <- list.append(Allrlt,rlt)
}
saveRDS(Allrlt, file = paste0(getwd(), "/", modelPath, "/rlt/rlt_Exp5.rds"))

```

# Merge the model Result data{-}
```{r include=FALSE}
#To preprocess the model result data, and merge different model version data together.
#function to merge the model result data
funMergeMRlt <- function(explist, path, modelversion){
  rltfilename <- {}
  rltfilename <- c(rltfilename, paste0("rlt_", explist, ".rds"))
  Bayparlist <- {}
  AllDat_predY <- {}
  AllDat_newY <- {}
  modelResultAll <- list()
  merge.data.all <- {}
  merge.data <- readRDS(file.path(paste0(getwd(), "/", path, "/rlt/", rltfilename[1])))
  for (i in 1:length(merge.data)){
    modelResultAll <- list.append(modelResultAll, merge.data[[i]])
    Bayparlist <- rbind(Bayparlist, merge.data[[i]]$Baypar)
    AllDat_predY <- rbind(AllDat_predY, merge.data[[i]]$PredY_list)
    AllDat_newY<- rbind(AllDat_newY, merge.data[[i]]$NewY_list)
  }
  
  if (length(rltfilename) >= 2) {
    for (i in 2:length(rltfilename)){
      new.data = readRDS(file.path(paste0(getwd(), "/", path, "/rlt/", rltfilename[i])))
      for (j in 1:length(new.data)){
        modelResultAll <- list.append(modelResultAll, new.data[[j]])
        Bayparlist <- rbind(Bayparlist, new.data[[j]]$Baypar)
        AllDat_predY <- rbind(AllDat_predY, new.data[[j]]$PredY_list)
        AllDat_newY<- rbind(AllDat_newY, new.data[[j]]$NewY_list)
      }
    }
  }
  write.csv(Bayparlist, paste0(getwd(), "/", path, "/rlt/AllDat_Bayparlist_", modelversion, ".csv"))
  write.csv(AllDat_predY, paste0( getwd(), "/",path, "/rlt/AllDat_predY_", modelversion, ".csv"))
  write.csv(AllDat_newY, paste0(getwd(), "/",path, "/rlt/AllDat_newY_", modelversion, ".csv"))
  saveRDS(modelResultAll, file = paste0(getwd(), "/", path, "/rlt/modelResultAll_", modelversion, ".rds")) 
}

funMergeMRlt('Exp5', modelPath, modelversion) # c('Exp1','Exp2','Exp3','Exp4', 'Exp5')
```

```{r}
dat_sub1 <- readRDS(file.path(paste0(getwd(), "/", modelPath, "/rlt/rlt_Exp5_sub1.rds")))

dat_sub1_predY <- dat_sub1$PredY_list
dat_sub1_newY <- dat_sub1$NewY_list

dat_sub1$PredY_list %>% group_by(Gap,WMSize) %>%
  summarise(m_wp = mean(wp),m_predY = mean(predY),m_mu_r = mean(mu_r),m_sig_r = mean(sig_r))


dat_sub1$NewY_list %>% group_by(Gap,WMSize) %>%
  summarise(m_wp = mean(wp),m_predY = mean(predY),m_mu_r = mean(mu_r),m_sig_r = mean(sig_r))

```




