---
title: "Figures for MS_Revision of WM_Reproduction"
author: "Jiao Wu"
date: "2023-08-23"
description: "adapted from 1.rstan_gap_report.Rmd and 2.linearmodel_gap_report.Rmd"
output: html_document:
    df_print: paged
    number_sections: true
  pdf_document: 
    number_sections: true
    latex_engine: xelatex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load packages and functions {-}
```{r include=FALSE}
library(rlist)
library(ez)
library(tidyverse)
library(latex2exp)
library(lsr)
library(rticles)
library(DescTools)
library(heplots)
library(lme4)
library(rstatix)
library(boot)
library(ggpubr)
library(reshape2)
```

```{r}
source('mytheme.R')
# model version
modelversion = 'gap_log_rstan'
rstanmodelPath = 'modelrlt'
modelPath = paste0(rstanmodelPath, '/models/', modelversion)
```

# 1. Load all behavioural data and Calculate correct rates for working memory task
```{r}
# (1) load all valid data for Exp 1-5
AllExpData = read.csv(paste0("../data/AllValidData.csv")) %>% filter(valid == 1)

dur <- sort(unique(AllExpData$curDur))
AllExpData$WMSize <- factor(AllExpData$WMSize, labels = c("low", "medium",  "high")) 
# Replace first 3 characters "Exp" with string "Exp. "
AllExpData$Exp <- gsub("^.{0,3}", "Exp. ", AllExpData$Exp)

# Exp 6
Data_Exp6 <- read.csv(paste0("../data/Exp6.csv")) %>% filter(valid == 1)
Data_Exp6$WMSize <- factor(Data_Exp6$WMSize, labels = c("low", "medium",  "high"))

# (2) calculate correct rates
AllExpData$WMCrr <- AllExpData$TPresent == AllExpData$WMRP
Data_Exp6$WMCrr <- Data_Exp6$TPresent == Data_Exp6$WMRP

# Exp 1-4
WMCrr <- dplyr::group_by(AllExpData, Exp, WMSize, NSub) %>% 
  dplyr::summarize(m_WMCrr = mean(WMCrr), n = n(), se_WMCrr = sd(WMCrr)/sqrt(n-1))
WMCrr %>% dplyr::group_by(Exp, WMSize) %>%
  dplyr::summarize( n = n(), mean_WMCrr = mean(m_WMCrr), se_WMCrr = sd(m_WMCrr)/sqrt(n-1) ) -> crrForExp1to4

# Exp 5
WMCrr_Exp5 = dplyr::group_by(AllExpData %>% filter(Exp =='Exp. 5'), WMSize, NSub, gap) %>% 
  dplyr::summarize(m_WMCrr = mean(WMCrr), n = n(), se_WMCrr = sd(WMCrr)/sqrt(n-1)) %>%
  dplyr::group_by(gap, WMSize) %>%
  dplyr::summarize( n = n(), mean_WMCrr = mean(m_WMCrr), se_WMCrr = sd(m_WMCrr)/sqrt(n-1))
WMCrr_Exp5$gap<- factor(WMCrr_Exp5$gap, labels = c("short", "long"))

# Exp 6
WMCrr_Exp6 <- dplyr::group_by(Data_Exp6, Exp, WMSize, NSub) %>% 
  dplyr::summarize(m_WMCrr = mean(WMCrr), n = n(), se_WMCrr = sd(WMCrr)/sqrt(n-1))
WMCrr_Exp6 %>% dplyr::group_by(Exp, WMSize) %>%
  dplyr::summarize( n = n(), mean_WMCrr = mean(m_WMCrr), se_WMCrr = sd(m_WMCrr)/sqrt(n-1) ) -> crrForExp6

```

# 2. plot correct rates for WM task
```{r}
# Exp 1
plt_WMCrr_Exp1 <- ggplot(subset(crrForExp1to4, Exp=="Exp. 1", select=c(Exp, WMSize, n, mean_WMCrr, se_WMCrr)), 
                    aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr,ymax = mean_WMCrr + se_WMCrr, group=Exp))+
  geom_line(stat = "identity",position = position_dodge(width = 0.2))+
  geom_point(size = 1.5, stat = "identity",position = position_dodge(width = 0.2))+ 
  geom_errorbar(width=.1,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy") +
  theme_new

# Exp 2
plt_WMCrr_Exp2 <- ggplot(subset(crrForExp1to4, Exp=="Exp. 2", select=c(Exp, WMSize, n, mean_WMCrr, se_WMCrr)), 
                    aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr,ymax = mean_WMCrr + se_WMCrr, group =Exp))+
  geom_line(stat = "identity",position = position_dodge(width = 0.2))+
  geom_point(size = 1.5, stat = "identity",position = position_dodge(width = 0.2))+ 
  geom_errorbar(width=.1,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy") +
  theme_new

# Exp 3
plt_WMCrr_Exp3 <- ggplot(subset(crrForExp1to4, Exp=="Exp. 3", select=c(Exp, WMSize, n, mean_WMCrr, se_WMCrr)), 
                    aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr,ymax = mean_WMCrr + se_WMCrr, group =Exp))+
  geom_line(stat = "identity",position = position_dodge(width = 0.2))+
  geom_point(size = 1.5, stat = "identity",position = position_dodge(width = 0.2))+ 
  geom_errorbar(width=.1,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy") +
  theme_new

# Exp 4
plt_WMCrr_Exp4 <- ggplot(subset(crrForExp1to4, Exp=="Exp. 4", select=c(Exp, WMSize, n, mean_WMCrr, se_WMCrr)), 
                    aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr,ymax = mean_WMCrr + se_WMCrr, group =Exp))+
  geom_line(stat = "identity",position = position_dodge(width = 0.2))+
  geom_point(size = 1.5, stat = "identity",position = position_dodge(width = 0.2))+ 
  geom_errorbar(width=.1,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy") +
  theme_new

# Exp 5
plt_WMCrr_Exp5 = ggplot(data = WMCrr_Exp5, 
                         aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr, 
                             ymax = mean_WMCrr + se_WMCrr, group = gap)) + 
  geom_line(aes(linetype = gap), stat = "identity",position = position_dodge(width = 0.3))+
  geom_point(size = 1.5, stat = "identity", position = position_dodge(width = 0.3))+ 
  geom_errorbar(width=.2,  position = position_dodge(width = 0.3)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy", linetype = "Gap") +
  theme_new + guides(linetype = FALSE)

# Exp 6
plt_WMCrr_Exp6 <- ggplot(crrForExp6, aes(WMSize, mean_WMCrr, ymin = mean_WMCrr - se_WMCrr, 
                                          ymax = mean_WMCrr + se_WMCrr, group = Exp))+
  geom_line(aes(linetype = Exp), stat = "identity",position = position_dodge(width = 0.2))+
  geom_point(size = 1.5, stat = "identity",position = position_dodge(width = 0.2))+ 
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.5, 1)) +
  labs(x = "Memory load", y = "Mean accuracy") +
  theme_new + theme(legend.position = "top", legend.justification = c(.8, .8), 
                    legend.text = element_text(size = 8), legend.title = element_text(size = 8, face = "bold"))

plt_WMCrr_Exp1
plt_WMCrr_Exp2
plt_WMCrr_Exp3
plt_WMCrr_Exp4
plt_WMCrr_Exp5
plt_WMCrr_Exp6

```



# 3. Load all model results and Calculate mean reproduction biases
```{r}
# (1) calculate mean reproduction bias
AllExpData$Exp = as.factor(AllExpData$Exp)

# mark the Gap condition in Exp5
Data_Exp5 <- AllExpData %>% filter(Exp == "Exp. 5")
Data_Exp5$gap <- factor(Data_Exp5$gap, labels = c("short", "long"))

# (2) calculate the mean reproduction biases for the 5 given intervals for all participants
mRpr_sub <- dplyr::group_by(AllExpData, curDur, Exp, NSub, WMSize) %>%
  dplyr::summarize(n = n(), 
                   m_repDur = mean(repDur),
                   sd_repDur = sd(repDur),
                   cv =sd_repDur/ m_repDur)

mRpr_sub_Exp5 <- dplyr::group_by(Data_Exp5, curDur, Exp, NSub, WMSize, gap) %>%
  dplyr::summarize(n = n(), 
                   m_repDur = mean(repDur),
                   sd_repDur = sd(repDur),
                   cv =sd_repDur/ m_repDur)

mRpr_sub_Exp6 <-  dplyr::group_by(Data_Exp6, curDur, Exp, NSub, WMSize) %>%
  dplyr::summarize(n = n(), 
                   m_repDur = mean(repDur),
                   sd_repDur = sd(repDur),
                   m_RT = mean(repWaitTime),
                   cv = sd_repDur/ m_repDur)

## calculate grand mean reproduction bias
mRpr <- mRpr_sub %>% dplyr::group_by(Exp, curDur, WMSize) %>% 
  dplyr::summarize(n = n(),
                   m_m_repDur = mean(m_repDur),
                   m_bias = mean(m_repDur-curDur),
                   sd_bias = sd(m_repDur-curDur)/sqrt(n-1),
                   m_cv= mean(cv),
                   sd_cv=sd(cv)/sqrt(n-1))

mRpr_Exp5 <- mRpr_sub_Exp5 %>% dplyr::group_by(Exp, curDur, WMSize, gap) %>% 
  dplyr::summarize(n = n(),
                   m_m_repDur = mean(m_repDur),
                   m_bias = mean(m_repDur-curDur),
                   sd_bias = sd(m_repDur-curDur)/sqrt(n-1),
                   m_cv= mean(cv),
                   sd_cv=sd(cv)/sqrt(n-1))

mRpr_Exp6 <- mRpr_sub_Exp6 %>% dplyr::group_by(Exp, curDur, WMSize) %>% 
  dplyr::summarize(n = n(),
                   m_m_repDur = mean(m_repDur),
                   m_bias = mean(m_repDur-curDur),
                   sd_bias = sd(m_repDur-curDur)/sqrt(n-1),
                   m_mRT = mean(m_RT),
                   sd_mRT = sd(m_RT)/sqrt(n-1),
                   m_cv= mean(cv),
                   sd_cv=sd(cv)/sqrt(n-1))

# mark valid RT in Exp6
# mRT_sub_Exp6_forFilter <-  dplyr::group_by(Data_Exp6, Exp, NSub) %>%
#   dplyr::summarize(n = n(),
#                    m_RT = mean(repWaitTime),
#                    sd_RT = sd(repWaitTime)/sqrt(n-1))
# mRT_sub_Exp6_forFilter$highThreshold = mRT_sub_Exp6_forFilter$m_RT + 3*mRT_sub_Exp6_forFilter$sd_RT

Data_Exp6$validRT <- Data_Exp6$repWaitTime >= 0.2 & Data_Exp6$repWaitTime <= 2.5
Data_Exp6_mRT <- Data_Exp6 %>% filter(validRT == TRUE)

mRT_sub_Exp6 <-  dplyr::group_by(Data_Exp6_mRT, curDur, Exp, NSub, WMSize) %>%
  dplyr::summarize(n = n(), m_RT = mean(repWaitTime))
mRT_Exp6 <- mRT_sub_Exp6 %>% dplyr::group_by(Exp, curDur, WMSize) %>% 
  dplyr::summarize(n = n(), m_mRT = mean(m_RT), sd_mRT = sd(m_RT)/sqrt(n-1))


```

# 4. plot mean Reproduction biases, mean Reproduction CV, and their estimated curves
```{r}
# plot mean Reproduction bias
# Exp 1
plt_RprBias_Exp1 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 1'),
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(-0.5, 0.4)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load")+
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 2
plt_RprBias_Exp2 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 2'),
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(-0.5, 0.4)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load")+
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 3
plt_RprBias_Exp3 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 3'),
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(-0.5, 0.4)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load")+
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 4
plt_RprBias_Exp4 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 4'),
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(-0.5, 0.4)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load")+
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 5
plt_RprBias_Exp5 <- ggplot(data = mRpr_Exp5,
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias, 
                               group=interaction(WMSize,gap),
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(linetype = gap), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(-0.5, 0.4)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load", linetype = "Gap") +
  theme_new + colorSet3 + 
  guides(linetype = guide_legend(order = 1),
         shape = guide_legend(order = 2), color = guide_legend(order = 2)) +
  theme(legend.position = "top", legend.justification = c(.6, .6), 
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))
 

# Exp 6
plt_RprBias_Exp6 <- ggplot(data = mRpr_Exp6,
                           aes(curDur, m_bias, ymin = m_bias - sd_bias, 
                               ymax = m_bias + sd_bias,
                               group=interaction(WMSize, Exp),
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",
            position = position_dodge(width = 0.2)) +
  geom_hline(yintercept = 0, linetype='dashed') +
  geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  facet_wrap("Exp") +
  coord_cartesian(ylim = c(-0.35, 0.2)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="", y="Reproduction bias (s)", 
       shape ="Memory Load", color = "Memory Load") +
  theme_new + colorSet3 + 
  theme(legend.position = "top", legend.justification = c("center", "top"),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"),
        strip.text = element_text(size=10, face = "bold"))

# Exp 6: response speed (from the onset of Reproduction cue to Reproduction onset)
plt_RT_Exp6 <- ggplot(data = mRT_Exp6,
                           aes(curDur, m_mRT, ymin = m_mRT - sd_mRT, 
                               ymax = m_mRT + sd_mRT,
                               group=interaction(WMSize, Exp),
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",
            position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  facet_wrap("Exp") +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Duration (s)", y="Reaction Time (s)", 
       shape ="Memory Load", color = "Memory Load") +
  theme_new + colorSet3 + 
  theme(legend.position = "top", legend.justification = c("center", "top"),
        legend.text = element_text(size = 8), legend.title = element_text(size = 8, face = "bold"),
        strip.text = element_text(size=10, face = "bold"))

# Exp 6: response speed (from the onset of Reproduction cue to Reproduction onset) for each participant
# plt_RT_Exp6Sub <- ggplot(data = mRT_sub_Exp6,
#                            aes(x=curDur, y=m_RT, group=interaction(WMSize, Exp),
#                                color=as.factor(WMSize), shape = as.factor(WMSize))) +
#   geom_line(aes(color = WMSize, linetype = Exp), stat = "identity",
#             position = position_dodge(width = 0.2)) +
#   geom_point(size = 2, stat = "identity",position = position_dodge(width = 0.2))+
#   facet_wrap("NSub") +
#   scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
#   labs(x="Duration (s)", y="Reaction Time (s)", 
#        shape ="Memory Load", color = "Memory Load", linetype = "Exp") +
#   theme_new + colorSet3 + 
#   theme(legend.position = "top", legend.justification = c("center", "top"),
#         legend.text = element_text(size = 8), legend.title = element_text(size = 10, face = "bold"),
#         strip.text = element_text(size=10, face = "bold"))
# plt_RT_Exp6Sub


plt_RprBias_Exp1
plt_RprBias_Exp2
plt_RprBias_Exp3
plt_RprBias_Exp4
plt_RprBias_Exp5
plt_RprBias_Exp6
plt_RT_Exp6
```

```{r}
# plot mean Reproduction CV

# Exp 1
plt_RprCV_Exp1 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 1'),
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.16, 0.28)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", color = "Memory Load", shape ="Memory Load")+ 
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 2
plt_RprCV_Exp2 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 2'), 
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.2, 0.35)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", color = "Memory Load", shape ="Memory Load")+ 
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 3
plt_RprCV_Exp3 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 3'), 
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.17, 0.29)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", color = "Memory Load", shape ="Memory Load")+ 
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 4
plt_RprCV_Exp4 <- ggplot(data = mRpr %>% filter(Exp == 'Exp. 4'), 
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group=WMSize,
                               color=as.factor(WMSize), shape = as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2,  position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.17, 0.31)) +
  scale_y_continuous(breaks=c(0.2, 0.25, 0.3)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", color = "Memory Load", shape ="Memory Load")+ 
  theme_new + colorSet3 +
  theme(legend.position = "top", legend.justification = c(.8, .8),
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Exp 5
plt_RprCV_Exp5 <- ggplot(data = mRpr_Exp5, 
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group = interaction(WMSize,gap),
                               color=as.factor(WMSize), shape=as.factor(WMSize))) +
  geom_line(aes(linetype = gap), stat = "identity",position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2, position = position_dodge(width = 0.2)) +
  coord_cartesian(ylim = c(0.15, 0.3)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", 
       color = "Memory Load", shape ="Memory Load", linetype = "Gap")+ 
  theme_new + colorSet3 + 
  guides(linetype = guide_legend(order = 1),
         shape = guide_legend(order = 2), color = guide_legend(order = 2)) +
  theme(legend.position = "top", legend.justification = c(.6, .6), 
        legend.text = element_text(size = 10), legend.title = element_text(size = 10, face = "bold"))

# Experiment 6
plt_RprCV_Exp6 <- ggplot(data  = mRpr_Exp6, 
                         aes(curDur, m_cv, ymin = m_cv - sd_cv, 
                               ymax = m_cv + sd_cv, group=interaction(WMSize, Exp),
                               color=as.factor(WMSize), shape=as.factor(WMSize))) +
  geom_line(aes(color = WMSize), stat = "identity", 
            position = position_dodge(width = 0.2)) +
  geom_point(size = 2, stat = "identity", position = position_dodge(width = 0.2))+
  geom_errorbar(width=.2, position = position_dodge(width = 0.2)) +
  facet_wrap("Exp") +
  coord_cartesian(ylim = c(0.15, 0.35)) +
  scale_x_continuous(breaks=c(0.5, 0.8, 1.1, 1.4, 1.7)) +
  labs(x="Durations (s)", y="CV (s)", 
       color = "Memory Load", shape ="Memory Load") +
  theme_new + colorSet3 + theme(strip.text = element_text(size=0, face = "bold")) +
  guides(color = FALSE, shape = FALSE)

plt_RprCV_Exp1
plt_RprCV_Exp2
plt_RprCV_Exp3
plt_RprCV_Exp4
plt_RprCV_Exp5
plt_RprCV_Exp6
```


# combine the figures for each experiment

```{r}

plt_Exp1 <- ggarrange(plt_WMCrr_Exp1, plt_RprBias_Exp1, plt_RprCV_Exp1, common.legend = TRUE, 
                      ncol=3, nrow=1, widths = c(4,4,4), labels = c("a", "b","c"))
plt_Exp1

plt_Exp2 <- ggarrange(plt_WMCrr_Exp2, plt_RprBias_Exp2, plt_RprCV_Exp2, common.legend = TRUE, 
                      ncol=3, nrow=1, widths = c(4,4,4), labels = c("a", "b","c"))
plt_Exp2

plt_Exp3 <- ggarrange(plt_WMCrr_Exp3, plt_RprBias_Exp3, plt_RprCV_Exp3, common.legend = TRUE, 
                      ncol=3, nrow=1, widths = c(4,4,4), labels = c("a", "b","c"))
plt_Exp3

plt_Exp4 <- ggarrange(plt_WMCrr_Exp4, plt_RprBias_Exp4, plt_RprCV_Exp4, common.legend = TRUE, 
                      ncol=3, nrow=1, widths = c(4,4,4), labels = c("a", "b","c"))
plt_Exp4

plt_Exp5 <- ggarrange(plt_WMCrr_Exp5, plt_RprBias_Exp5, plt_RprCV_Exp5, common.legend = TRUE, 
                      ncol=3, nrow=1, widths = c(4,4,4), labels = c("a", "b","c"))
plt_Exp5

plt_Exp6_1 <- ggarrange(plt_WMCrr_Exp6, plt_RT_Exp6, common.legend = FALSE, 
                      ncol=2, nrow=1, widths = c(3,6), labels = c("a", "b"))
plt_Exp6_1

plt_Exp6 <- ggarrange(plt_RprBias_Exp6, plt_RprCV_Exp6, labels=c("a", "b"), nrow = 2, heights = c(9,8))
plt_Exp6

ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp1.png"), plt_Exp1, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp2.png"), plt_Exp2, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp3.png"), plt_Exp3, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp4.png"), plt_Exp4, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp5.png"), plt_Exp5, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_WMCrr_Exp6.png"), plt_WMCrr_Exp6, width = 3, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp6_1.png"), plt_Exp6_1, width = 8.5, height = 3.54)
ggsave(paste0(getwd(), "/figures/plt_FigRvs2_Exp6.png"), plt_Exp6, width = 6, height = 6)
```



